### ISSUE TITLE
Ranger Sword 2 and Sword 3 IDs swapped

### ISSUE THREAD

**Issue by Stomper2** [campbt/DanceDanceRotationComposer#2]
So sorry to bother again.

After some testing, it appears that the ID for Ranger's sword 3 and sword 2 are swapped. The dps report (https://dps.report/KXbi-20231003-200539_golem) has the order of 2-4-3 and the generated output is 3-4-2:

```{
            "time": 2112,
            "duration": 848,
            "noteType": "Weapon3",
            "abilityId": 69203
        },
        {
            "time": 2960,
            "duration": 432,
            "noteType": "Weapon4",
            "abilityId": 12638
        },
        {
            "time": 3392,
            "duration": 1008,
            "noteType": "Weapon2",
            "abilityId": 12482
        },

**Comment by campbt** [comment]
I think that's ability optimization feature failing for some reason. If you toggle that off, it will switch back to 2,4,3. I'm looking into why it tried to move those around.

**Comment by Stomper2** [comment]
It seems to be staying the same. Only the timing changes (as it's supposed to)

**Comment by campbt** [comment]
Sorry, I tested on a local one that had the new scraped data for skills. That seems to have been the problem. I've pushed up a new version, can you please try it on that, I think it's working with the ability queue feature as well.

**Comment by Stomper2** [comment]
That works. Thank you :D

**Comment by campbt** [comment]
Thanks for letting me know. I've also released a new Blish module which should fix the broken icons in the module for the new SotO skills (basically, some new skill IDs for existing weapons when used on new elite specializations)
